### ISSUE TITLE
Error after build app in electron (no idea how to handle react element)

### ISSUE THREAD

**Issue by Sheidaas** [Bucky24/react-canvas-map#16]
After I build version in electron, I see that react cannot render layers. 
I dont know why this error is happening. When I was running this on developer server - everything was okay.
Could you please help me with this?
              
This is a code which I used in my app.
```
    Canvas width={955} height={700}>
        <Map x={10} y={10} zoomType={{type:'NONE'}} width={this.state.dimensions.width} height={this.state.dimensions.height}
        cellSize={this.state.scaleList[this.state.scaleIndex][0]} zoom={this.state.scaleList[this.state.scaleIndex][1]}
        minCellX={-this.xOff} minCellY={-this.yOff} maxCellX={this.maxCellX}
        maxCellY={this.maxCellY}
        onClick={(x, y, button, rawX, rawY) => this.onMapClick(x, y, button, rawX, rawY)}>
            <Layer>
                <LayerImage xOff={-this.xOff} yOff={-this.yOff} src={this.getMapByName(this.state.CurrentMap)} x={0} y={0}
                                width={this.state.dimensions.width} height={this.state.dimensions.height} />
            </Layer>
            
            <Layer>
                <LayerRaw cells={this.instances} drawFunc={this.drawInstance} />
            </Layer>

            <Layer>
                <LayerRaw cells={this.farmbot_waypoints} drawFunc={this.drawFarmbotWaypoint} />
            </Layer>
            <Layer>
                <LayerRaw cells={[{cellX:this.props.character_status.Position[0]/100-this.xOff, cellY:this.props.character_status.Position[1]/100-this.yOff, cellWidth:this.props.hack_status.WaitHack.Range/100}]} drawFunc={this.drawWaithackRangeCircle} />
            </Layer>
            <Layer>
                <LayerRaw cells={[{cellX:this.props.character_status.Position[0]/100-this.xOff, cellY:this.props.character_status.Position[1]/100-this.yOff, cellWidth:this.props.hack_status.Settings.PickupRange/100}]} drawFunc={this.drawPickupRangeCircle} />

            </Layer>
        </Map>
        </Canvas>
```

**Comment by Bucky24** [comment]
Interesting. I've seen a similar issue before where the map was drawing fine in the browser except for 1 user that just couldn't see anything at all. I'm still not sure what caused it for them but I wonder if it's the same root cause. I imagine it's something in the way that electron is reporting the size of some part of the window, or it could be something about the rendering system in react-canvas that's acting up.

Are you able to create a repo with a minimal project that shows this bug that I can play around in? There could be a lot of variables that are leading to this happening, and it would be a lot easier for me to debug that than try to guess all the possible things that could be causing it.

**Comment by Sheidaas** [comment]
I invitied you to repository with this code. Is there a better way to speak than here?

**Comment by Bucky24** [comment]
This is probably the best place to talk.

I've got your code running. How do I get it to the point where the map is showing up? I can get to the dashboard but not anything further. It looks like there's supposed to be a client list, but I don't see anything there.

**Comment by Bucky24** [comment]
Ah actually, can you provide any more detail about that error? That is from the react-canvas custom rendering system (which react-canvas-map uses for clipping). It should tell you which element it couldn't render. I probably have to update that engine to handle something. There should be a console log telling you what the type of element was just before the error shows up.

**Comment by Bucky24** [comment]
Looking at your draw code, all of your draw methods can return undefined. I'm not 100% sure if the system handles that correctly, so that might be the issue. Hard to tell without reproducing it though.

Can you try returning some stub drawable element in your draw functions at the end? Something like

```
<Rect x={0} y={0} x2={1} y2={1} />
```

If that fixes the issue, then I know what can be done to prevent it from happening. If not, I'll have to keep digging.

**Comment by Sheidaas** [comment]
So, the whole project is kinda big - it is manager for bots for mmo game metin2, and if you want see any client you need inject dll to game, and run python websocket server to see anything. Thats why for me it is kinda hard to mock this map.
The whole component with map is in components/MetinClientMap/MetinClientMap
The error point to second layer, RawLayer with instances. ImageLayer was occuring error after I deleted every RawLayer.
Error https://ibb.co/Njj6P2c, working app https://ibb.co/L1FHqQc
Sorry for the trouble, i will check that

**Comment by Bucky24** [comment]
Oh wow that looks really cool!

Ok yeah I can see why that would be hard to mock up. Thanks for the error. That seems like it's a standard React element so not sure why the system broke on it. There should be a console log right above that, can you send that as well?

**Comment by Sheidaas** [comment]
The whole console looks like that https://ibb.co/DWXKGPb

**Comment by Bucky24** [comment]
Hmmm... It looks like it's getting a Context, but not recognizing it as a Context. I'm going to do some testing, maybe fragments changed and it's not recognizing them anymore. Still not sure why it would be doing this for Electron but not the browser.

**Comment by Sheidaas** [comment]
Btw If I am using electron to load url localhost:3000 which i am already running dev server, map is rendering without any error

**Comment by Bucky24** [comment]
Interesting. What are you doing to load it the other way when it doesn't render?

**Comment by Sheidaas** [comment]
I thought it could be that I made mistake with load static files - but in dev console in application tab I see image is returning correct.
Honestly, I dont know what is happening here

**Comment by Sheidaas** [comment]
And it looks like rendering rect in every case is not fixing this.

**Comment by Bucky24** [comment]
Ok, well I'm going to see if I can get this to happen myself so I can fix it.  I am also confused as to why this is happening. Hopefully I can figure something out-I'll keep you up to date.

**Comment by Sheidaas** [comment]
Thank you very much

**Comment by Bucky24** [comment]
Ok so it does look like for some reason there's a context there that doesn't have the `_context` param on it, so it's not being recognized.

This appears to be coming from `Images`, which is one of the few things that still uses that old-style version of a Context.

**Comment by Bucky24** [comment]
Ok, I have modified the system to detect a Context via checking the name on the symbol which should always be present. Can you please try updating `@bucky24/react-canvas` to version `1.7.1` and see if that fixes your issue?

**Comment by Sheidaas** [comment]
yes it did. Thank you very much, you save this project :D

**Comment by Bucky24** [comment]
Awesome! I'm glad to hear it! Let me know if you have any other issues. Very happy to see that people are finding this work useful!
